# # Análise de arrecadação de IPVA no estado do Rio de Janeiro


Este projeto tem como objetivo analisar a arrecadação tributária no estado do Rio de Janeiro, considerando valores arrecadados por município e por região administrativa.

A análise utiliza uma série histórica dos últimos cinco anos de arrecadação do seguinte tributo estadual:

- IPVA (Imposto sobre a Propriedade de Veículos Automotores)

Os dados são disponibilizados publicamente pelo portal de dados abertos do governo brasileiro, reunindo informações de arrecadação tributária divulgadas pela Secretaria de Fazenda do Estado do Rio de Janeiro.

Fonte dos dados: dados.gov.br  
Link direto: https://dados.gov.br/dados/conjuntos-dados/arrecadacao-receitas  

Última atualização do dataset: 28/07/2025  

Fase atual da análise: **Tratamento de dados**

In [1]:
# Importações
import pandas as pd

In [2]:
df = pd.read_csv(
    "../data/00_03_arrecadacao_por_municipio_e_regiao_ipva-2017.csv",
    sep=";",
    skiprows=2,          # ignora as linhas de título e ";;;;;;;;"
    encoding="latin1",   # funciona melhor para arquivos brasileiros antigos
    engine="python",
    decimal=",",
    thousands=".",
    index_col=False
)

C:\Users\samue\AppData\Local\Temp\ipykernel_8624\831044609.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(

In [3]:
df.head()

,Regiï¿½/ Municï¿½o,Janeiro,Fevereiro,Marï¿½Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,BAIXADAS LITORï¿½EAS,46327190.67,29338614.97,23906407.38,13944494.19,7111693.59,5765980.59,5282980.99,4861707.96,3631253.29,2881701.40,1937152.92
1,ARARUAMA,5499064.37,3587746.70,3070719.76,1870401.42,951973.15,724117.04,692563.70,665014.90,483490.27,390837.50,251095.72
2,ARMACAO DE BUZIOS,2899656.20,1968671.63,1377890.22,822523.50,370058.23,304156.87,264208.89,276428.04,238889.24,215926.30,151302.58
3,ARRAIAL DO CABO,1389101.25,831078.30,695238.83,396987.24,216519.39,152048.40,150634.02,128394.08,90167.27,82533.68,53348.60
4,CABO FRIO,11595135.85,7492964.60,6219131.72,3581646.30,1754444.91,1419880.92,1294806.43,1196768.31,897946.49,722503.99,508129.32

In [4]:
df.shape

(102, 12)

In [5]:
df.columns

Index(['Regiï¿½/ Municï¿½o', 'Janeiro', 'Fevereiro', 'Marï¿½Abril', 'Maio',
       'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro',
       'Dezembro'],
      dtype='str')

In [6]:
df.columns = [
    "Regiao_Municipio",
    "Janeiro",
    "Fevereiro",
    "Marco_Abril",
    "Maio",
    "Junho",
    "Julho",
    "Agosto",
    "Setembro",
    "Outubro",
    "Novembro",
    "Dezembro",
    
]

In [7]:
df.head()

,Regiao_Municipio,Janeiro,Fevereiro,Marco_Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,BAIXADAS LITORï¿½EAS,46327190.67,29338614.97,23906407.38,13944494.19,7111693.59,5765980.59,5282980.99,4861707.96,3631253.29,2881701.40,1937152.92
1,ARARUAMA,5499064.37,3587746.70,3070719.76,1870401.42,951973.15,724117.04,692563.70,665014.90,483490.27,390837.50,251095.72
2,ARMACAO DE BUZIOS,2899656.20,1968671.63,1377890.22,822523.50,370058.23,304156.87,264208.89,276428.04,238889.24,215926.30,151302.58
3,ARRAIAL DO CABO,1389101.25,831078.30,695238.83,396987.24,216519.39,152048.40,150634.02,128394.08,90167.27,82533.68,53348.60
4,CABO FRIO,11595135.85,7492964.60,6219131.72,3581646.30,1754444.91,1419880.92,1294806.43,1196768.31,897946.49,722503.99,508129.32

In [8]:
df["Regiao_Municipio"] = df["Regiao_Municipio"].replace(
    "BAIXADAS LITORï¿½EAS",
    "BAIXADAS LITORANEAS"
)

In [9]:
df.head()

,Regiao_Municipio,Janeiro,Fevereiro,Marco_Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,BAIXADAS LITORANEAS,46327190.67,29338614.97,23906407.38,13944494.19,7111693.59,5765980.59,5282980.99,4861707.96,3631253.29,2881701.40,1937152.92
1,ARARUAMA,5499064.37,3587746.70,3070719.76,1870401.42,951973.15,724117.04,692563.70,665014.90,483490.27,390837.50,251095.72
2,ARMACAO DE BUZIOS,2899656.20,1968671.63,1377890.22,822523.50,370058.23,304156.87,264208.89,276428.04,238889.24,215926.30,151302.58
3,ARRAIAL DO CABO,1389101.25,831078.30,695238.83,396987.24,216519.39,152048.40,150634.02,128394.08,90167.27,82533.68,53348.60
4,CABO FRIO,11595135.85,7492964.60,6219131.72,3581646.30,1754444.91,1419880.92,1294806.43,1196768.31,897946.49,722503.99,508129.32

Trataremos de casos Similares agora, buscando e formatando regioes e municipios.

In [10]:
# todas as regioes e municipios
regioes_municipios = df["Regiao_Municipio"].to_list()
print(regioes_municipios)

['BAIXADAS LITORANEAS', 'ARARUAMA', 'ARMACAO DE BUZIOS', 'ARRAIAL DO CABO', 'CABO FRIO', 'CACHOEIRAS DE MACACU', 'CASIMIRO DE ABREU', 'IGUABA GRANDE', 'RIO BONITO', 'RIO DAS OSTRAS', 'SAO PEDRO DA ALDEIA', 'SAQUAREMA', 'SILVA JARDIM', 'CAPITAL', 'RIO DE JANEIRO', 'CENTRO SUL', 'AREAL', 'COMENDADOR LEVY GASPARIAN', 'ENGENHEIRO PAULO DE FRONTIN', 'MENDES', 'MIGUEL PEREIRA', 'PARAIBA DO SUL', 'PATY DO ALFERES', 'SAPUCAIA', 'TRES RIOS', 'VASSOURAS', 'LITORAL SUL FLUMINENSE', 'ANGRA DOS REIS', 'MANGARATIBA', 'PARATI', 'Mï¿½IO PARAï¿½A', 'BARRA DO PIRAI', 'BARRA MANSA', 'ITATIAIA', 'PINHEIRAL', 'PIRAI', 'PORTO REAL', 'QUATIS', 'RESENDE', 'RIO CLARO', 'RIO DAS FLORES', 'VALENCA', 'VOLTA REDONDA', 'METROPOLITANA', 'BELFORD ROXO', 'DUQUE DE CAXIAS', 'GUAPIMIRIM', 'ITABORAI', 'ITAGUAI', 'JAPERI', 'MAGE', 'MARICA', 'MESQUITA', 'NILOPOLIS', 'NITEROI', 'NOVA IGUACU', 'PARACAMBI', 'QUEIMADOS', 'SAO GONCALO', 'SAO JOAO DE MERITI', 'SEROPEDICA', 'TANGUA', 'NOROESTE', 'APERIBE', 'BOM JESUS DO ITABAPOANA', 'CAMBUCI', 'ITALVA', 'ITAOCARA', 'ITAPERUNA', 'LAJE DO MURIAE', 'MIRACEMA', 'NATIVIDADE', 'PORCIUNCULA', 'SANTO ANTONIO DE PADUA', 'SAO JOSE DE UBA', 'VARRE SAI', 'NORTE', 'CAMPOS DOS GOYTACAZES', 'CARAPEBUS', 'CARDOSO MOREIRA', 'CONCEICAO DE MACABU', 'MACAE', 'QUISSAMA', 'SAO FIDELIS', 'SAO FRANCISCO DE ITABAPOANA', 'SAO JOAO DA BARRA', 'SERRANA', 'BOM JARDIM', 'CANTAGALO', 'CARMO', 'CORDEIRO', 'DUAS BARRAS', 'MACUCO', 'NOVA FRIBURGO', 'PETROPOLIS', 'SANTA MARIA MADALENA', 'SAO JOSE DO VALE DO RIO PRETO', 'SAO SEBASTIAO DO ALTO', 'SUMIDOURO', 'TERESOPOLIS', 'TRAJANO DE MORAIS', 'Total Geral']

* Mais um problema de formatação desta vez em Mï¿½IO PARAï¿½A

In [11]:
correcoes = {
    "BAIXADAS LITORï¿½EAS": "BAIXADAS LITORANEAS",
    "Mï¿½IO PARAï¿½A": "MEDIO PARAIBA"
}

df["Regiao_Municipio"] = df["Regiao_Municipio"].replace(correcoes)

In [12]:

regioes_municipios = df["Regiao_Municipio"].to_list()
print(regioes_municipios)

['BAIXADAS LITORANEAS', 'ARARUAMA', 'ARMACAO DE BUZIOS', 'ARRAIAL DO CABO', 'CABO FRIO', 'CACHOEIRAS DE MACACU', 'CASIMIRO DE ABREU', 'IGUABA GRANDE', 'RIO BONITO', 'RIO DAS OSTRAS', 'SAO PEDRO DA ALDEIA', 'SAQUAREMA', 'SILVA JARDIM', 'CAPITAL', 'RIO DE JANEIRO', 'CENTRO SUL', 'AREAL', 'COMENDADOR LEVY GASPARIAN', 'ENGENHEIRO PAULO DE FRONTIN', 'MENDES', 'MIGUEL PEREIRA', 'PARAIBA DO SUL', 'PATY DO ALFERES', 'SAPUCAIA', 'TRES RIOS', 'VASSOURAS', 'LITORAL SUL FLUMINENSE', 'ANGRA DOS REIS', 'MANGARATIBA', 'PARATI', 'MEDIO PARAIBA', 'BARRA DO PIRAI', 'BARRA MANSA', 'ITATIAIA', 'PINHEIRAL', 'PIRAI', 'PORTO REAL', 'QUATIS', 'RESENDE', 'RIO CLARO', 'RIO DAS FLORES', 'VALENCA', 'VOLTA REDONDA', 'METROPOLITANA', 'BELFORD ROXO', 'DUQUE DE CAXIAS', 'GUAPIMIRIM', 'ITABORAI', 'ITAGUAI', 'JAPERI', 'MAGE', 'MARICA', 'MESQUITA', 'NILOPOLIS', 'NITEROI', 'NOVA IGUACU', 'PARACAMBI', 'QUEIMADOS', 'SAO GONCALO', 'SAO JOAO DE MERITI', 'SEROPEDICA', 'TANGUA', 'NOROESTE', 'APERIBE', 'BOM JESUS DO ITABAPOANA', 'CAMBUCI', 'ITALVA', 'ITAOCARA', 'ITAPERUNA', 'LAJE DO MURIAE', 'MIRACEMA', 'NATIVIDADE', 'PORCIUNCULA', 'SANTO ANTONIO DE PADUA', 'SAO JOSE DE UBA', 'VARRE SAI', 'NORTE', 'CAMPOS DOS GOYTACAZES', 'CARAPEBUS', 'CARDOSO MOREIRA', 'CONCEICAO DE MACABU', 'MACAE', 'QUISSAMA', 'SAO FIDELIS', 'SAO FRANCISCO DE ITABAPOANA', 'SAO JOAO DA BARRA', 'SERRANA', 'BOM JARDIM', 'CANTAGALO', 'CARMO', 'CORDEIRO', 'DUAS BARRAS', 'MACUCO', 'NOVA FRIBURGO', 'PETROPOLIS', 'SANTA MARIA MADALENA', 'SAO JOSE DO VALE DO RIO PRETO', 'SAO SEBASTIAO DO ALTO', 'SUMIDOURO', 'TERESOPOLIS', 'TRAJANO DE MORAIS', 'Total Geral']

Os problemas de formatação foram devidamente Superados

In [13]:
df.dtypes

Regiao_Municipio        str
Janeiro             float64
Fevereiro           float64
Marco_Abril         float64
Maio                float64
Junho               float64
Julho               float64
Agosto              float64
Setembro            float64
Outubro             float64
Novembro            float64
Dezembro            float64
dtype: object

In [14]:
df["Regiao_Municipio"].head(15)

0      BAIXADAS LITORANEAS
1                 ARARUAMA
2        ARMACAO DE BUZIOS
3          ARRAIAL DO CABO
4                CABO FRIO
5     CACHOEIRAS DE MACACU
6        CASIMIRO DE ABREU
7            IGUABA GRANDE
8               RIO BONITO
9           RIO DAS OSTRAS
10     SAO PEDRO DA ALDEIA
11               SAQUAREMA
12            SILVA JARDIM
13                 CAPITAL
14          RIO DE JANEIRO
Name: Regiao_Municipio, dtype: str

In [15]:
df["Regiao_Municipio"].unique()

<ArrowStringArray>
[          'BAIXADAS LITORANEAS',                      'ARARUAMA',
             'ARMACAO DE BUZIOS',               'ARRAIAL DO CABO',
                     'CABO FRIO',          'CACHOEIRAS DE MACACU',
             'CASIMIRO DE ABREU',                 'IGUABA GRANDE',
                    'RIO BONITO',                'RIO DAS OSTRAS',
 ...
                        'MACUCO',                 'NOVA FRIBURGO',
                    'PETROPOLIS',          'SANTA MARIA MADALENA',
 'SAO JOSE DO VALE DO RIO PRETO',         'SAO SEBASTIAO DO ALTO',
                     'SUMIDOURO',                   'TERESOPOLIS',
             'TRAJANO DE MORAIS',                   'Total Geral']
Length: 102, dtype: str

In [16]:
df = df[df["Regiao_Municipio"] != "Total Geral"]

In [17]:
df.shape

(101, 12)

In [18]:
df.tail(15)

,Regiao_Municipio,Janeiro,Fevereiro,Marco_Abril,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
86,SERRANA,60335451.22,33890575.66,24295829.95,14671627.01,6905015.68,5573243.77,4508373.14,4266903.95,3167640.19,2519886.71,1899432.79
87,BOM JARDIM,1514642.73,828009.26,568022.82,344876.93,177261.20,127242.44,132046.91,93828.15,53878.14,56465.71,39955.21
88,CANTAGALO,902499.95,515928.48,391812.47,209441.33,106325.52,76970.84,76798.30,61624.62,36134.37,31522.12,20141.33
89,CARMO,690783.98,370050.71,286900.06,152142.70,60371.32,39627.85,46073.80,34804.56,27310.14,26153.92,13024.16
90,CORDEIRO,1073014.06,671881.26,530106.45,293968.45,157658.98,147717.00,89953.81,72350.30,50303.36,33418.23,31208.66
91,DUAS BARRAS,377345.34,228950.28,163222.71,100513.96,49351.74,41950.70,33841.84,29594.45,24735.10,7730.15,12452.27
92,MACUCO,303104.94,176553.57,162525.19,85528.86,39221.66,39699.83,28942.13,17137.96,17402.97,13576.78,13301.06
93,NOVA FRIBURGO,15848374.34,8581926.45,6098757.59,3560847.12,1670290.93,1513501.83,1082178.24,1019744.38,782487.17,545841.70,401644.72
94,PETROPOLIS,23749883.80,13980891.30,9788107.37,6285625.84,2785716.66,2059358.89,1821836.25,1782531.43,1351384.11,1127128.35,693806.21
95,SANTA MARIA MADALENA,362851.34,203482.55,139519.75,87852.13,47075.52,34086.80,26043.41,23454.28,10007.34,8342.97,6316.13
96,SAO JOSE DO VALE DO RIO PRETO,1138737.68,549008.43,434280.32,263292.33,108982.07,72805.05,56702.11,71736.53,40231.69,26809.73,40205.39
97,SAO SEBASTIAO DO ALTO,361220.91,181139.64,167316.45,78517.08,47399.42,41778.32,26603.02,37104.77,18260.95,18726.29,13556.78
98,SUMIDOURO,753690.67,379665.58,226542.70,137210.32,96928.60,86577.42,50467.64,41939.33,27790.57,30240.40,21870.99
99,TERESOPOLIS,12974204.95,7040505.02,5192450.19,2965442.05,1521033.71,1257412.95,1002997.59,952607.75,712009.15,584104.25,582951.19
100,TRAJANO DE MORAIS,285096.53,182583.13,146265.88,106367.91,37398.35,34513.85,33888.09,28445.44,15705.13,9826.11,8998.69

In [19]:
df = df.rename(columns={
    "Marco_Abril": "Marco"
})

In [20]:
df.head()

,Regiao_Municipio,Janeiro,Fevereiro,Marco,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
0,BAIXADAS LITORANEAS,46327190.67,29338614.97,23906407.38,13944494.19,7111693.59,5765980.59,5282980.99,4861707.96,3631253.29,2881701.40,1937152.92
1,ARARUAMA,5499064.37,3587746.70,3070719.76,1870401.42,951973.15,724117.04,692563.70,665014.90,483490.27,390837.50,251095.72
2,ARMACAO DE BUZIOS,2899656.20,1968671.63,1377890.22,822523.50,370058.23,304156.87,264208.89,276428.04,238889.24,215926.30,151302.58
3,ARRAIAL DO CABO,1389101.25,831078.30,695238.83,396987.24,216519.39,152048.40,150634.02,128394.08,90167.27,82533.68,53348.60
4,CABO FRIO,11595135.85,7492964.60,6219131.72,3581646.30,1754444.91,1419880.92,1294806.43,1196768.31,897946.49,722503.99,508129.32

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df["Regiao_Municipio"].duplicated().sum()

np.int64(0)

In [23]:
df.isnull().sum()

Regiao_Municipio    0
Janeiro             0
Fevereiro           0
Marco               0
Maio                0
Junho               0
Julho               0
Agosto              0
Setembro            0
Outubro             0
Novembro            0
Dezembro            0
dtype: int64

In [24]:
df.describe()

,Janeiro,Fevereiro,Marco,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
count,1.010000e+02,1.010000e+02,1.010000e+02,1.010000e+02,1.010000e+02,1.010000e+02,1.010000e+02,1.010000e+02,1.010000e+02,1.010000e+02,1.010000e+02
mean,1.959703e+07,1.182827e+07,8.300845e+06,4.893459e+06,2.411604e+06,1.982217e+06,1.760248e+06,1.630180e+06,1.233246e+06,9.519325e+05,6.810188e+05
std,7.620053e+07,4.594893e+07,3.045951e+07,1.800433e+07,8.674226e+06,7.148359e+06,6.430305e+06,5.823425e+06,4.434899e+06,3.470331e+06,2.467872e+06
min,1.877958e+05,1.085559e+05,8.240148e+04,4.957765e+04,2.255893e+04,1.883376e+04,1.339980e+04,1.057404e+04,5.478960e+03,6.573970e+03,4.489630e+03
25%,6.907840e+05,3.861436e+05,3.214404e+05,1.754987e+05,9.692860e+04,7.040775e+04,5.632519e+04,5.803990e+04,3.733387e+04,3.024040e+04,2.187099e+04
50%,1.780864e+06,1.051398e+06,7.924600e+05,4.745720e+05,2.451257e+05,1.877320e+05,1.740611e+05,1.623140e+05,1.297076e+05,8.791254e+04,6.898106e+04
75%,8.923927e+06,5.388758e+06,4.127883e+06,2.394318e+06,1.283781e+06,1.002501e+06,8.885713e+05,8.698168e+05,5.958211e+05,4.535997e+05,3.254143e+05
max,5.253630e+08,3.154783e+08,2.061105e+08,1.218350e+08,5.833979e+07,4.796674e+07,4.310922e+07,3.886731e+07,2.959122e+07,2.324366e+07,1.653638e+07

In [25]:
df.sort_values("Janeiro", ascending=False).head(10)

,Regiao_Municipio,Janeiro,Fevereiro,Marco,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
14,RIO DE JANEIRO,5.253630e+08,3.154783e+08,2.061105e+08,1.218350e+08,58339789.20,47966740.87,43109219.88,38867312.53,29591216.11,23243659.86,16536376.98
13,CAPITAL,5.253630e+08,3.154783e+08,2.061105e+08,1.218350e+08,58339789.20,47966740.87,43109219.88,38867312.53,29591216.11,23243659.86,16536376.98
43,METROPOLITANA,2.151409e+08,1.367249e+08,1.033661e+08,6.094940e+07,30645848.23,25688157.46,23411825.56,21684810.62,16541118.82,12667272.66,8949575.52
54,NITEROI,6.252063e+07,3.819828e+07,2.315306e+07,1.379142e+07,6798918.47,5694641.52,5033739.07,4588124.27,3491397.37,2725975.15,2061939.18
86,SERRANA,6.033545e+07,3.389058e+07,2.429583e+07,1.467163e+07,6905015.68,5573243.77,4508373.14,4266903.95,3167640.19,2519886.71,1899432.79
30,MEDIO PARAIBA,5.754784e+07,3.074796e+07,2.136872e+07,1.303623e+07,7309647.91,5670361.23,4462037.62,4357902.31,3122128.10,2036373.31,1726583.11
0,BAIXADAS LITORANEAS,4.632719e+07,2.933861e+07,2.390641e+07,1.394449e+07,7111693.59,5765980.59,5282980.99,4861707.96,3631253.29,2881701.40,1937152.92
76,NORTE,4.393407e+07,2.712184e+07,2.181108e+07,1.248445e+07,6491586.75,5556529.64,4636933.11,4793410.64,3752287.33,2769364.58,1958584.20
58,SAO GONCALO,3.109815e+07,2.005952e+07,1.658760e+07,9.740376e+06,4441255.21,3663243.71,3195324.75,3097340.50,2462352.04,1874135.32,1388871.25
45,DUQUE DE CAXIAS,2.803335e+07,1.856300e+07,1.500015e+07,8.910217e+06,4157025.81,3425089.29,3362279.40,3154436.46,2461058.63,1964419.21,1211615.34

In [26]:
df = df[df["Regiao_Municipio"] != "CAPITAL"]

In [27]:
df.sort_values("Janeiro", ascending=False).head(10)

,Regiao_Municipio,Janeiro,Fevereiro,Marco,Maio,Junho,Julho,Agosto,Setembro,Outubro,Novembro,Dezembro
14,RIO DE JANEIRO,5.253630e+08,3.154783e+08,2.061105e+08,1.218350e+08,58339789.20,47966740.87,43109219.88,38867312.53,29591216.11,23243659.86,16536376.98
43,METROPOLITANA,2.151409e+08,1.367249e+08,1.033661e+08,6.094940e+07,30645848.23,25688157.46,23411825.56,21684810.62,16541118.82,12667272.66,8949575.52
54,NITEROI,6.252063e+07,3.819828e+07,2.315306e+07,1.379142e+07,6798918.47,5694641.52,5033739.07,4588124.27,3491397.37,2725975.15,2061939.18
86,SERRANA,6.033545e+07,3.389058e+07,2.429583e+07,1.467163e+07,6905015.68,5573243.77,4508373.14,4266903.95,3167640.19,2519886.71,1899432.79
30,MEDIO PARAIBA,5.754784e+07,3.074796e+07,2.136872e+07,1.303623e+07,7309647.91,5670361.23,4462037.62,4357902.31,3122128.10,2036373.31,1726583.11
0,BAIXADAS LITORANEAS,4.632719e+07,2.933861e+07,2.390641e+07,1.394449e+07,7111693.59,5765980.59,5282980.99,4861707.96,3631253.29,2881701.40,1937152.92
76,NORTE,4.393407e+07,2.712184e+07,2.181108e+07,1.248445e+07,6491586.75,5556529.64,4636933.11,4793410.64,3752287.33,2769364.58,1958584.20
58,SAO GONCALO,3.109815e+07,2.005952e+07,1.658760e+07,9.740376e+06,4441255.21,3663243.71,3195324.75,3097340.50,2462352.04,1874135.32,1388871.25
45,DUQUE DE CAXIAS,2.803335e+07,1.856300e+07,1.500015e+07,8.910217e+06,4157025.81,3425089.29,3362279.40,3154436.46,2461058.63,1964419.21,1211615.34
55,NOVA IGUACU,2.395181e+07,1.576973e+07,1.220001e+07,7.156679e+06,4292206.07,3666208.88,3395935.58,3110354.54,2260795.18,1597019.50,1086487.31

In [28]:
df.reset_index(drop=True, inplace=True)

In [29]:
df.to_csv("ipva_rj_2017_tratado.csv", index=False)

## Conclusão do Processo de Tratamento de Dados

Este notebook teve como objetivo realizar o **tratamento e preparação dos dados de arrecadação de IPVA do estado do Rio de Janeiro referentes ao ano de 2017**, com foco em transformar um arquivo bruto em um **dataset limpo, consistente e pronto para análise**.

Durante o processo foram identificados diversos problemas estruturais no arquivo original, o que exigiu uma abordagem investigativa e incremental. Entre os principais desafios encontrados estão:

* **Problemas de codificação (encoding)** que resultaram em caracteres corrompidos, como “ï¿½”, afetando nomes de regiões e municípios.
* **Cabeçalhos inconsistentes**, incluindo colunas com nomes incorretos ou unificados de forma indevida (ex.: meses combinados como “Março/Abril”).
* **Formatação inadequada dos valores numéricos**, que utilizavam separadores de milhar e vírgula decimal no padrão brasileiro, dificultando a conversão para valores numéricos utilizáveis em análise.
* **Presença de linhas agregadas**, como “Total Geral”, que não representam observações individuais e poderiam distorcer análises estatísticas.
* **Duplicação conceitual**, como a coexistência das entradas “CAPITAL” e “RIO DE JANEIRO”, que representavam a mesma entidade.
* **Mistura de níveis de agregação**, pois o dataset apresenta tanto **municípios individuais** quanto **regiões administrativas**, sendo estas últimas compostas pela soma de vários municípios.

Ao longo do notebook foram aplicadas diversas técnicas de limpeza e organização de dados, incluindo:

* correção de codificação e padronização de texto;
* ajuste e renomeação de colunas;
* separação e reorganização de campos;
* conversão de valores monetários para formato numérico adequado;
* remoção de registros agregados ou redundantes;
* verificação de valores nulos, duplicidades e tipos de dados;
* validação estatística básica do dataset.

O processo também evidenciou a importância de **exploração e validação contínua dos dados**, utilizando ferramentas como ordenação de valores, inspeção de tipos (`dtypes`), estatísticas descritivas e análise de unicidade.

Como resultado final, foi produzido um **dataset estruturado e confiável**, contendo registros mensais de arrecadação de IPVA por região ou município, com valores numéricos padronizados e sem inconsistências estruturais relevantes.

Este conjunto de dados tratado será salvo como uma **versão final limpa**, que servirá de base para a próxima etapa do projeto:
a **análise exploratória e geração de visualizações**, a serem desenvolvidas em um novo notebook dedicado à interpretação dos dados, construção de gráficos e elaboração de relatórios analíticos.

Dessa forma, este notebook cumpre o papel fundamental de **etapa de preparação de dados (Data Cleaning / Data Preparation)** dentro do fluxo de trabalho de análise de dados, garantindo que as análises posteriores sejam realizadas sobre informações confiáveis e bem estruturadas.